apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  DB_NAME: postgres
  DB_USER: postgres
  DB_HOST: postgresdb
  DB_PORT: '5432'
---
apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  DB_PASSWORD: djdkV1gwdWlMNw==