apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-app
  name: backend-app
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 5153
      targetPort: 5153
  selector:
    service: backend-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-app
  name: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend-app
  template:
    metadata:
      labels:
        service: backend-app
    spec:
      containers:
        - image: 927143137470.dkr.ecr.us-east-1.amazonaws.com/xuda_devops_p3:0.0.1
          name: backend-app
          imagePullPolicy: Always
          ports:
            - containerPort: 5153
          livenessProbe:
            httpGet:
              path: /health_check
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /readiness_check
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "2048Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: configmap
      restartPolicy: Always