apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-app
  name: backend-app
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 5153
      targetPort: 5153
  selector:
    service: backend-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking
  labels:
    name: coworking
spec:
  replicas: 1
  selector:
    matchLabels:
      service: coworking
  template:
    metadata:
      labels:
        service: coworking
    spec:
      containers:
      - name: coworking
        image: <DOCKER_IMAGE_URI_FROM_ECR> TODO
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 5
        envFrom:
        - configMapRef:
            name: configmap
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: <NAME OF THE Secret> TODO
              key: <THE KEY FROM Secret WHICH has THE ENCODED PASSWORD> TODO
      restartPolicy: Always