apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: coworking-space-service
  region: us-east-1

vpc:
  id: vpc-007e727a29265471d # need to update value after run network
  cidr: "10.0.0.0/16"
  subnets:
    public:
      us-east-1a:
        id: subnet-0ef132fee6acc6db3	 # need to update value after run network
      us-east-1b:
        id: subnet-04019b2b4b39cd8ed  # need to update value after run network

managedNodeGroups:
  - name: xuda-devops-p3-WorkerNode
    instanceType: t3.medium
    minSize: 1
    desiredCapacity: 1
    maxSize: 3

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]